% system_scaling - Generalized system scaling function using database scaling laws
%
% This function provides a generalized entry point for computing subsystem masses
% and powers using database-derived scaling laws with adaptive mass-fraction correction.
% It aggregates component-level scaling laws from CSV files in Database/Scaling/,
% applies margins, and ensures proper mass distribution across subsystems.
%
% Syntax:
%   [systemmasses, systempowers] = system_scaling(data)
%
% Input:
%   data - Structure containing spacecraft parameters with fields:
%          .mass             - Total spacecraft mass [kg]
%          .dv (optional)    - Delta-v requirement [m/s]
%          .c_e (optional)   - Effective exhaust velocity [m/s]
%          .mass_propellant (optional) - Propellant mass [kg]
%          .power_total (optional)     - Total power [W]
%
% Outputs:
%   systemmasses - Structure containing mass breakdown:
%                  .m_dry_nomargin   - Dry mass without margin [kg]
%                  .m_margin         - System margin mass [kg]
%                  .m_dry_margin     - Dry mass available after margin [kg]
%                  .mass_propellant  - Propellant mass [kg]
%                  .mass_payload     - Payload mass [kg]
%                  .mass_structmech  - Structure/mechanism mass [kg]
%                  .mass_thermal     - Thermal control mass [kg]
%                  .mass_power       - Power subsystem mass [kg]
%                  .mass_ttc         - TT&C subsystem mass [kg]
%                  .mass_adc         - ADCS subsystem mass [kg]
%                  .mass_propulsion  - Propulsion subsystem mass [kg]
%                  .mass_other       - Other subsystems mass [kg]
%
%   systempowers - Structure containing power breakdown:
%                  .power_total         - Total spacecraft power [W]
%                  .power_payload       - Payload power [W]
%                  .power_structmech    - Structure/mechanism power [W]
%                  .power_thermal       - Thermal control power [W]
%                  .power_power         - Power subsystem power [W]
%                  .power_ttc           - TT&C power [W]
%                  .power_adc           - ADCS power [W]
%                  .propulsion_power    - Propulsion power [W]
%
% Algorithm:
%   1. Determine spacecraft type (LEO, GEO, planetary, etc.)
%   2. Calculate baseline dry mass (m_dry_nomargin) using rocket equation or direct input
%   3. Apply standard margin factor based on spacecraft type
%   4. For each subsystem:
%      a. Attempt to read scaling law from Database/Scaling/ CSV files
%      b. Fall back to SMAD-based scaling if CSV not available
%      c. Apply scaling law to compute subsystem mass/power
%   5. Apply adaptive mass-fraction correction:
%      a. Calculate total allocated mass from subsystems
%      b. Compare with available m_dry_margin
%      c. Distribute discrepancy proportionally across subsystems
%      d. Limit adjustments to avoid unreasonable changes
%   6. Recalculate final margin mass
%
% Notes:
%   - This function maintains backward compatibility with SMAD_scalings interface
%   - CSV scaling files are generated by update_scaling_model() from database
%   - Adaptive correction preserves mass margins while respecting physical constraints
%
% See also: SMAD_scalings, scale_SMAD_parameter, determine_sc_type, scaling_linear
%
% References:
%   Wertz, J., Everett, D., Puschell, J. (2011). Space Mission Engineering: 
%   The New SMAD. Microcosm Press.

function [systemmasses, systempowers] = system_scaling(data)
    
    % Initialize output structures
    systemmasses = struct;
    systempowers = struct;
    
    % Determine spacecraft type and baseline masses
    sc_type = determine_sc_type(data);
    systemmasses.m_dry_nomargin = determine_m_dry(data);
    
    % Calculate and apply margin
    systemmasses.m_margin = m_margin(systemmasses.m_dry_nomargin, sc_type);
    systemmasses.m_dry_margin = systemmasses.m_dry_nomargin - systemmasses.m_margin;
    
    % Calculate propellant mass
    systemmasses.mass_propellant = data.mass - systemmasses.m_dry_nomargin;
    
    % Aggregate mass scaling laws from database
    systemmasses = aggregate_mass_scaling(systemmasses, sc_type, data);
    
    % Apply adaptive mass-fraction correction
    systemmasses = apply_adaptive_correction(systemmasses, sc_type);
    
    % Recalculate margin after corrections
    systemmasses.m_dry_margin = systemmasses.mass_payload + systemmasses.mass_structmech + ...
                                systemmasses.mass_thermal + systemmasses.mass_power + ...
                                systemmasses.mass_ttc + systemmasses.mass_adc + ...
                                systemmasses.mass_propulsion + systemmasses.mass_other;
    
    systemmasses.m_margin = systemmasses.m_dry_nomargin - systemmasses.m_dry_margin;
    
    if systemmasses.m_margin < 0
        disp('Warning: No system margin remaining after scaling');
    end
    
    % Aggregate power scaling laws
    systempowers = aggregate_power_scaling(systemmasses, sc_type, data);
    
endfunction


%% Helper Functions

function [m_dry] = determine_m_dry(data)
    % Calculate dry mass using rocket equation or direct specification
    % Reuses exact logic from SMAD_scalings for consistency
    if isfield(data,'dv') && isfield(data,'c_e')
        m_dry = exp(-data.dv/data.c_e) * data.mass;
    elseif isfield(data,'mass_propellant')
        m_dry = data.mass - data.mass_propellant;
    else
        m_dry = data.mass;
    endif
endfunction


function m = m_margin(m_dry, sc_type)
    % Calculate margin mass based on spacecraft type
    % Uses NASA GSFC-STD-1000 standard margin factors
    factor = [0.25 0.25 0.25 0.25];  % 25% margin for all types
    m = m_dry * factor(sc_type);
endfunction


function systemmasses = aggregate_mass_scaling(systemmasses, sc_type, data)
    % Aggregate subsystem masses using database scaling laws where available
    % Falls back to SMAD scaling when database entries are not present
    
    base_mass = systemmasses.m_dry_margin;
    
    % Define subsystem names and their corresponding parameter mappings
    subsystems = {
        'mass_payload',     'fraction_mass_payload';
        'mass_structmech',  'fraction_mass_structmech';
        'mass_thermal',     'fraction_mass_thermal';
        'mass_power',       'fraction_mass_power';
        'mass_ttc',         'fraction_mass_TTC';
        'mass_adc',         'fraction_mass_ADC';
        'mass_propulsion',  'fraction_mass_propulsion';
        'mass_other',       'fraction_mass_other'
    };
    
    % Apply scaling for each subsystem
    for i = 1:size(subsystems, 1)
        field_name = subsystems{i, 1};
        fraction_param = subsystems{i, 2};
        
        % Try to use database scaling, fall back to SMAD
        try
            fraction = scale_parameter_with_fallback(base_mass, sc_type, ...
                                                     'mass_total', fraction_param);
            systemmasses.(field_name) = fraction * base_mass;
        catch
            % If scaling fails, use default fractions
            systemmasses.(field_name) = get_default_mass_fraction(sc_type, ...
                                                                  fraction_param) * base_mass;
        end
    end
    
endfunction


function systempowers = aggregate_power_scaling(systemmasses, sc_type, data)
    % Aggregate subsystem powers using database scaling laws
    
    systempowers = struct;
    
    % Determine total power
    if isfield(data, 'power_total')
        systempowers.power_total = data.power_total;
    else
        systempowers.power_total = p_tot_average(systemmasses.m_dry_nomargin, sc_type);
    endif
    
    % Define power subsystems and their parameter mappings
    power_subsystems = {
        'power_payload',      'fraction_power_payload';
        'power_structmech',   'fraction_power_structmech';
        'power_thermal',      'fraction_power_thermal';
        'power_power',        'fraction_power_power';
        'power_ttc',          'fraction_power_TTC';
        'power_adc',          'fraction_power_ADC';
        'propulsion_power',   'fraction_propulsion_power'
    };
    
    % Apply scaling for each power subsystem
    for i = 1:size(power_subsystems, 1)
        field_name = power_subsystems{i, 1};
        fraction_param = power_subsystems{i, 2};
        
        try
            fraction = scale_parameter_with_fallback(systempowers.power_total, sc_type, ...
                                                     'power_total', fraction_param);
            systempowers.(field_name) = fraction * systempowers.power_total;
        catch
            systempowers.(field_name) = get_default_power_fraction(sc_type, ...
                                                                   fraction_param) * systempowers.power_total;
        end
    end
    
endfunction


function fraction = scale_parameter_with_fallback(input_value, sc_type, param_a, param_b)
    % Attempt to scale using database CSV, fall back to SMAD scaling
    
    % First try the existing scale_SMAD_parameter which reads from CSV
    sc_name = {"No Propulsion"; "Low Earth"; "High Earth"; "Planetary"};
    filename = strcat("Database/Scaling/scaling_spacecraft_", char(sc_name{sc_type, 1}), ...
                     "_parameter_", param_a, "_to_", param_b, ".csv");
    
    if exist(filename, "file")
        data = dlmread(filename, ",");
        fraction = scaling_linear(input_value, data);
    else
        % Fall back to fixed SMAD fractions
        fraction = get_default_mass_fraction(sc_type, param_b);
    endif
    
endfunction


function systemmasses = apply_adaptive_correction(systemmasses, sc_type)
    % Apply adaptive mass-fraction correction to ensure sum matches available dry margin
    % while avoiding unreasonable fraction changes
    
    % Calculate initial total allocated mass
    allocated_mass = systemmasses.mass_payload + systemmasses.mass_structmech + ...
                    systemmasses.mass_thermal + systemmasses.mass_power + ...
                    systemmasses.mass_ttc + systemmasses.mass_adc + ...
                    systemmasses.mass_propulsion + systemmasses.mass_other;
    
    % Calculate discrepancy
    target_mass = systemmasses.m_dry_margin;
    discrepancy = target_mass - allocated_mass;
    
    % Only apply correction if discrepancy is significant (> 0.1%)
    if abs(discrepancy) / target_mass > 0.001
        
        % Define max adjustment factor to prevent unreasonable changes
        max_adjustment_factor = 1.15;  % Allow up to 15% change in any subsystem
        min_adjustment_factor = 0.85;  % Allow up to 15% reduction
        
        % Calculate proportional weights for distribution
        % Use current allocations as weights
        weights = [
            systemmasses.mass_payload;
            systemmasses.mass_structmech;
            systemmasses.mass_thermal;
            systemmasses.mass_power;
            systemmasses.mass_ttc;
            systemmasses.mass_adc;
            systemmasses.mass_propulsion;
            systemmasses.mass_other
        ];
        
        total_weight = sum(weights);
        if total_weight > 0
            % Distribute discrepancy proportionally
            adjustments = (weights / total_weight) * discrepancy;
            
            % Apply adjustments with limits
            subsystem_fields = {'mass_payload', 'mass_structmech', 'mass_thermal', ...
                               'mass_power', 'mass_ttc', 'mass_adc', ...
                               'mass_propulsion', 'mass_other'};
            
            for i = 1:length(subsystem_fields)
                field = subsystem_fields{i};
                original = systemmasses.(field);
                adjusted = original + adjustments(i);
                
                % Ensure adjustment stays within reasonable bounds
                if adjusted / original > max_adjustment_factor
                    adjusted = original * max_adjustment_factor;
                elseif adjusted / original < min_adjustment_factor
                    adjusted = original * min_adjustment_factor;
                endif
                
                % Ensure non-negative mass
                if adjusted < 0
                    adjusted = 0;
                endif
                
                systemmasses.(field) = adjusted;
            end
        endif
    endif
    
endfunction


function P = p_tot_average(mass_dry, sc_type)
    % Calculate average total power based on dry mass and spacecraft type
    % Based on SMAD Tab 14-20
    power_factor = [299 794 691 749];
    mass_factor = mass_dry ./ [1497 2344 1258 888];
    P = mass_factor(sc_type)^(2/3) * power_factor(sc_type);
endfunction


function fraction = get_default_mass_fraction(sc_type, param_name)
    % Return default SMAD mass fractions when database scaling not available
    % Based on SMAD Tab 14-18
    
    % Define default fractions for each spacecraft type
    % Columns: [No Propulsion, LEO, High Earth, Planetary]
    default_fractions = struct();
    default_fractions.fraction_mass_payload     = [0.31 0.22 0.15 0.15];
    default_fractions.fraction_mass_structmech  = [0.22 0.17 0.22 0.23];
    default_fractions.fraction_mass_thermal     = [0.03 0.04 0.04 0.04];
    default_fractions.fraction_mass_power       = [0.19 0.27 0.17 0.16];
    default_fractions.fraction_mass_TTC         = [0.04 0.04 0.08 0.09];
    default_fractions.fraction_mass_ADC         = [0.07 0.06 0.08 0.08];
    default_fractions.fraction_mass_propulsion  = [0.00 0.06 0.13 0.11];
    default_fractions.fraction_mass_other       = [0.14 0.14 0.13 0.14];
    
    if isfield(default_fractions, param_name)
        fraction = default_fractions.(param_name)(sc_type);
    else
        fraction = 0.1;  % Generic fallback
    endif
endfunction


function fraction = get_default_power_fraction(sc_type, param_name)
    % Return default SMAD power fractions when database scaling not available
    % Based on SMAD power distribution tables
    
    % Define default power fractions for each spacecraft type
    default_fractions = struct();
    default_fractions.fraction_power_payload       = [0.40 0.35 0.30 0.30];
    default_fractions.fraction_power_structmech    = [0.05 0.05 0.05 0.05];
    default_fractions.fraction_power_thermal       = [0.10 0.12 0.12 0.12];
    default_fractions.fraction_power_power         = [0.10 0.10 0.10 0.10];
    default_fractions.fraction_power_TTC           = [0.10 0.08 0.15 0.15];
    default_fractions.fraction_power_ADC           = [0.10 0.10 0.13 0.13];
    default_fractions.fraction_propulsion_power    = [0.00 0.10 0.15 0.15];
    
    if isfield(default_fractions, param_name)
        fraction = default_fractions.(param_name)(sc_type);
    else
        fraction = 0.1;  % Generic fallback
    endif
endfunction
