% volume_scalings  — Estimate spacecraft geometry from total mass via scaling laws
%
% Uses the spacecraft reference database scaling laws (derived from real spacecraft
% size_x, size_y, size_h, and computed volume_box fields) to estimate the bounding
% box geometry of a design point.
%
% The scaling laws are piecewise-linear fits generated by update_scaling_model from
% the ESDC_Reference_Data_Spacecrafts database, one CSV per (orbit type, parameter)
% pair.  volume_box is derived as size_x * size_y * size_h in the database and
% cross-checked here with the direct product of the three estimated dimensions.
%
% Parameters:
%   data    : individual struct with fields .mass and orbit/propulsion info
%             (same struct passed to SMAD_scalings)
%   sc_type : integer spacecraft type index (1=No Prop, 2=LEO, 3=HEO, 4=Planetary)
%             Optional if data already contains sc_type-determining fields.
%             If omitted, determine_sc_type(data) is called internally.
%
% Returns:
%   geom    : struct with fields
%     .size_x     [m]   — estimated bounding box width
%     .size_y     [m]   — estimated bounding box depth
%     .size_h     [m]   — estimated bounding box height
%     .volume_box [m³]  — product size_x * size_y * size_h (bounding box volume)
%     .volume_box_scaled [m³] — volume estimated directly from mass_total→volume_box
%                               scaling law (independent cross-check)
%
% Notes:
%   - All quantities are statistical estimates based on historical spacecraft data.
%   - When a scaling CSV does not exist (e.g. no data for that sc_type), the
%     corresponding field is set to NaN.
%   - volume_box is the primary volume metric reported in the design output.
%     volume_box_scaled is provided as a sanity-check cross-reference.

function geom = volume_scalings(data, sc_type)

  if nargin < 2
    sc_type = determine_sc_type(data);
  end

  m = data.mass;

  geom.size_x           = safe_scale(m, sc_type, 'mass_total', 'size_x');
  geom.size_y           = safe_scale(m, sc_type, 'mass_total', 'size_y');
  geom.size_h           = safe_scale(m, sc_type, 'mass_total', 'size_h');
  geom.volume_box       = geom.size_x * geom.size_y * geom.size_h;
  geom.volume_box_scaled = safe_scale(m, sc_type, 'mass_total', 'volume_box');

end


% -------------------------------------------------------------------------
% safe_scale — wrapper around scale_SMAD_parameter that returns NaN when the
% required CSV is missing rather than producing an error.
% -------------------------------------------------------------------------
function y = safe_scale(mass, sc_type, param_a, param_b)
  sc_name = {'No Propulsion'; 'Low Earth'; 'High Earth'; 'Planetary'};
  filename = strcat('Database/Scaling/scaling_spacecraft_', char(sc_name{sc_type}), ...
                    '_parameter_', param_a, '_to_', param_b, '.csv');
  if exist(filename, 'file')
    y = scale_SMAD_parameter(mass, sc_type, param_a, param_b);
    if isnan(y) || y < 0
      y = NaN;
    end
  else
    y = NaN;
  end
end
